In [1]:
import numpy as np

In [13]:
a1 = np.empty((2, 2))
print("1. Empty array (2x2):\n", a1)


1. Empty array (2x2):
 [[8.16702459e-316 0.00000000e+000]
 [5.31410685e-317 6.73479118e-310]]


In [14]:
a2 = np.ones((4, 2))
print("2. All ones array (4x2):\n", a2)


2. All ones array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [15]:
a3 = np.full((3, 3), fill_value=7)
print("3. Array filled with 7 (3x3):\n", a3)


3. Array filled with 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [16]:
given = np.array([[1, 2], [3, 4]])
a4 = np.zeros_like(given)
print("4. Zeros like given array:\n", a4)


4. Zeros like given array:
 [[0 0]
 [0 0]]


In [17]:
a5 = np.ones_like(given)
print("5. Ones like given array:\n", a5)


5. Ones like given array:
 [[1 1]
 [1 1]]


In [18]:
new_list = [1, 2, 3, 4]
a6 = np.array(new_list)
print("6. Converted list to numpy array:\n", a6)


6. Converted list to numpy array:
 [1 2 3 4]


In [19]:
arr21 = np.arange(10, 50)
print("2.1 Array from 10 to 49:\n", arr21)


2.1 Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [20]:
arr22 = np.arange(9).reshape((3, 3))
print("2.2 3x3 matrix from 0 to 8:\n", arr22)


2.2 3x3 matrix from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
arr23 = np.eye(3)
print("2.3 3x3 Identity matrix:\n", arr23)


2.3 3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
arr24 = np.random.random(30)
print("2.4 Random array of size 30:\n", arr24)
print("Mean of the array:", arr24.mean())


2.4 Random array of size 30:
 [0.06327225 0.4555803  0.60120944 0.51334946 0.79691178 0.31904799
 0.28974417 0.96820355 0.71221591 0.84752094 0.47625696 0.67487167
 0.1167127  0.50745726 0.45770238 0.50608715 0.75661215 0.27614547
 0.04729759 0.51376628 0.07204102 0.71579387 0.00712272 0.16452621
 0.41917329 0.86410009 0.02854834 0.48107149 0.26883203 0.27479939]
Mean of the array: 0.43986579498334993


In [23]:
arr25 = np.random.random((10, 10))
print("2.5 10x10 random array:\n", arr25)
print("Min value:", arr25.min())
print("Max value:", arr25.max())


2.5 10x10 random array:
 [[0.72501682 0.2060406  0.09788943 0.07305664 0.23153078 0.53874365
  0.90215981 0.38176751 0.93925169 0.57023832]
 [0.35559121 0.17012275 0.47737344 0.17369443 0.37251275 0.22532798
  0.62313561 0.5160547  0.02154545 0.11617803]
 [0.17065044 0.51393654 0.85377792 0.26225031 0.15392938 0.42795249
  0.05784237 0.69228366 0.00543188 0.97099953]
 [0.16708811 0.51395799 0.50554792 0.51805951 0.29069238 0.58122281
  0.30546805 0.01670967 0.43900361 0.50233799]
 [0.89440809 0.42700601 0.07109509 0.59769139 0.98590431 0.5480774
  0.20305339 0.07970488 0.48358089 0.23110684]
 [0.42215474 0.31758765 0.11153669 0.37099658 0.98192231 0.96537058
  0.8899692  0.1147345  0.76870123 0.34287553]
 [0.83181856 0.0864446  0.90643109 0.40130376 0.98730591 0.31639909
  0.84354353 0.05522272 0.40084176 0.84386935]
 [0.27959074 0.9335241  0.42160125 0.40256392 0.35375496 0.04696403
  0.13374241 0.11045151 0.35526254 0.56749247]
 [0.78380736 0.07241749 0.92109394 0.97443876 0.1214603 

In [24]:
arr26 = np.zeros(10)
arr26[4] = 1  # Index 4 is 5th element (0-based)
print("2.6 Zero array with 5th element set to 1:\n", arr26)


2.6 Zero array with 5th element set to 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [25]:
arr27 = np.array([1, 2, 0, 0, 4, 0])
arr27_rev = arr27[::-1]
print("2.7 Reversed array:\n", arr27_rev)


2.7 Reversed array:
 [0 4 0 0 2 1]


In [26]:
arr28 = np.ones((5, 5))
arr28[1:-1, 1:-1] = 0
print("2.8 2D array with 1 on border and 0 inside:\n", arr28)


2.8 2D array with 1 on border and 0 inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [27]:
arr29 = np.zeros((8, 8), dtype=int)
arr29[1::2, ::2] = 1
arr29[::2, 1::2] = 1
print("2.9 Checkerboard pattern (8x8):\n", arr29)


2.9 Checkerboard pattern (8x8):
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [28]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y
print("3.1 Add x and y:\n", add_xy)

# 2. Subtract the two arrays
sub_xy = x - y
print("\n3.2 Subtract y from x:\n", sub_xy)

# 3. Multiply the array with integers of choice (say multiply by 3)
mul_x = x * 3
print("\n3.3 Multiply x by 3:\n", mul_x)

# 4. Find the square of each element in x
square_x = x ** 2
print("\n3.4 Square of each element in x:\n", square_x)

# 5. Dot product between v and w; x and v; x and y
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\n3.5 Dot product v·w:", dot_vw)
print("Dot product x·v:\n", dot_xv)
print("Dot product x·y:\n", dot_xy)

# 6. Concatenate x and y along row (axis=0) and concatenate v and w along column (axis=0 is only for 2D, so use np.vstack for 1D vectors)
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.vstack((v, w))
print("\n3.6 Concatenate x and y along rows:\n", concat_xy_row)
print("Concatenate v and w along columns:\n", concat_vw_col)

# 7. Concatenate x and v - this will error due to shape mismatch. Catch and explain.
try:
    concat_xv = np.concatenate((x, v))
except ValueError as e:
    error_message = str(e)
print("\n3.7 Concatenate x and v results in error:")
print(error_message)
print("Explanation: Cannot concatenate arrays with different dimensions/shapes.")


3.1 Add x and y:
 [[ 6  8]
 [10 13]]

3.2 Subtract y from x:
 [[-4 -4]
 [-4 -3]]

3.3 Multiply x by 3:
 [[ 3  6]
 [ 9 15]]

3.4 Square of each element in x:
 [[ 1  4]
 [ 9 25]]

3.5 Dot product v·w: 219
Dot product x·v:
 [29 77]
Dot product x·y:
 [[19 22]
 [50 58]]

3.6 Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 10]
 [11 12]]

3.7 Concatenate x and v results in error:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: Cannot concatenate arrays with different dimensions/shapes.


In [29]:
# Problem 4 — Matrix Operations

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove that A * A^-1 = I
A_inv = np.linalg.inv(A)
result1 = A @ A_inv
print("4.1 A · A^-1:\n", result1)

# 2. Show that AB != BA
AB = A @ B
BA = B @ A
print("\n4.2 AB:\n", AB)
print("BA:\n", BA)
print("AB == BA?", np.array_equal(AB, BA))

# 3. Prove that (AB)^T = B^T A^T
lhs = (A @ B).T
rhs = B.T @ A.T
print("\n4.3 (AB)^T:\n", lhs)
print("B^T A^T:\n", rhs)
print("Check equality:", np.array_equal(lhs, rhs))


4.1 A · A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

4.2 AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB == BA? False

4.3 (AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]
Check equality: True


In [30]:
A2 = np.array([[2, -3, 1],
               [1, -1, 2],
               [3, 1, -1]])
B2 = np.array([-1, -3, 9])

# Solve using np.linalg.solve
X = np.linalg.solve(A2, B2)
print("Solution of the system [x, y, z]:\n", X)


Solution of the system [x, y, z]:
 [ 2.  1. -2.]


In [33]:
import time

N = 1_000_000   # 1D array size
M = 1000        # 2D matrix size

print("\n4.2 Experiment: How Fast is NumPy?\n")

# 1. Element-wise addition
list1 = list(range(N))
list2 = list(range(N))
arr1 = np.arange(N)
arr2 = np.arange(N)

start = time.time()
list_add = [list1[i]+list2[i] for i in range(N)]
end = time.time()
print("Python list addition time:", end-start)

start = time.time()
np_add = arr1 + arr2
end = time.time()
print("NumPy array addition time:", end-start)

# 2. Element-wise multiplication
start = time.time()
list_mul = [list1[i]*list2[i] for i in range(N)]
end = time.time()
print("\nPython list multiplication time:", end-start)

start = time.time()
np_mul = arr1 * arr2
end = time.time()
print("NumPy array multiplication time:", end-start)

# 3. Dot product
start = time.time()
dot_list = sum(list1[i]*list2[i] for i in range(N))
end = time.time()
print("\nPython list dot product time:", end-start)

start = time.time()
dot_np = np.dot(arr1, arr2)
end = time.time()
print("NumPy dot product time:", end-start)

# 4. Matrix multiplication
A = [[i+j for j in range(M)] for i in range(M)]
B = [[i*j for j in range(M)] for i in range(M)]

def python_matrix_mul(A,B):
    result = [[0]*M for _ in range(M)]
    for i in range(M):
        for j in range(M):
            s=0
            for k in range(M):
                s+=A[i][k]*B[k][j]
            result[i][j]=s
    return result

start = time.time()
python_matrix_mul(A,B)
end = time.time()
print("\nPython matrix multiplication time:", end-start)

A_np = np.array(A)
B_np = np.array(B)
start = time.time()
C_np = A_np @ B_np
end = time.time()
print("NumPy matrix multiplication time:", end-start)

print("\n4.2 Experiment Complete ")



4.2 Experiment: How Fast is NumPy?

Python list addition time: 0.1242671012878418
NumPy array addition time: 0.002273082733154297

Python list multiplication time: 0.14519119262695312
NumPy array multiplication time: 0.0024497509002685547

Python list dot product time: 0.10693240165710449
NumPy dot product time: 0.0019876956939697266

Python matrix multiplication time: 181.81572937965393
NumPy matrix multiplication time: 2.5571184158325195

4.2 Experiment Complete 
